---
- name: Install Docker 
  hosts: docker
  become: true
  vars_prompt:
    - name: username
      prompt: Enter username for acess in NGINX
      private: no
    - name: passwd
      prompt: Wait a password for NGINX user
  tasks:
    - name: Was Docker installed?
      command: 'systemctl status "{{ item }}"'
      register: package_check
      ignore_errors: true
      loop:
        - docker
      register: docker

    - name: Docker's block
      block:

        - name: Check result
          debug:
            var: docker.failed

        - name: Add Ubuntu Universe
          apt_repository:
            repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
            state: present

        - name: Add Key Docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg

        - name: Preinstall Docker Packages
          apt:
            name: "{{ item }}"
            state: present
            update_cache: no
          with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
            - htpasswd

        - name: Add Docker Universe
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update_cache: no

        - name: Install Docker
          apt: 
            name: "{{ item }}"
            state: present
          with_items:
           - docker
           - docker.io

        - name: Check Installed Docker
          service:
            name: docker
            state: restarted
            enabled: yes

      when: docker['failed'] == true
      
    - name: NGINX block
      block:

        - name: htpasswd
          command: 'htpasswd -c -b /etc/nginx/.htpasswd {{ username }} {{ passwd }}'

        - name: Copy conf file
          ansible.builtin.template:
            src: ~/ansible/default
            dest: /etc/nginx/sites-enabled/default

        - name: Copy site file
          ansible.builtin.template:
            src: ~/ansible/index.html
            dest: /var/www/html/index.html 

        - name: Check Installed Docker
          service:
            name: nginx
            state: restarted
            enabled: yes
